name: Test Demo Workflow

on: [push]

jobs:
  job-1:
    runs-on: ubuntu-latest
    steps:
      - name: Greeting Step
        run: echo "Hello CI/CD Pipeline"

      - name: Checkout code in VM
        uses: actions/checkout@v4

      - name: Installing Dependencies
        run: npm ci

      - name: Testing the flow
        run: npm run test

      - name: Starting the server and listening
        run: |
          npm run start &
          sleep 5
          curl -s -w "\nHTTP Status: %{http_code}\n" --fail http://localhost:3000/greet