name: Test Demo Workflow

on: [push]

jobs:
  linting-check:
    runs-on: ubuntu-latest

    steps:
      - name: Greeting to Linting step
        run: echo "Welcome to Linting step"

      - name: Extract Folders and files
        uses: actions/checkout@v4

      - name: Setting up the NODE Environment
        uses: actions/setup-node@v4
        with: 
          node-version: "24"
          cache: "npm"

      - name: Installing Dependencies
        run: npm install
      
      - name: Checking Linting errors
        run: npm run lint

  environment-check:
    runs-on: ubuntu-latest

    steps:
      - name: Greeting to Environment step
        run: echo "Welcome to Environment step"

      - name: Printing Environment Variables
        run: 
          echo "Secret Variable is $SEC"
          echo "Varibales Variable is $VAR"
          echo "Credentials is $CRED"
        env:
          SEC: ${{secrets.SEC}}
          VAR: ${{vars.DATABASEURI}}
          CRED: ${{vars.CRED}}

  connectivity-check:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:16
        env:
          POSTGRES_USER: ${{vars.CRED}}
          POSTGRES_PASSWORD: ${{vars.CRED}}
          POSTGRES_DB: ${{vars.CRED}}
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      - name: Greeting Step
        run: echo "Hello Welcome to Connection checking"

      - name: Checkout code in VM
        uses: actions/checkout@v4

      - name: Setting up the NODE Environment
        uses: actions/setup-node@v4
        with: 
          node-version: "24"
          cache: "npm"

      - name: Installing Dependencies
        run: npm install

      - name: Testing the flow
        run: npm run test
        env:
          DATABASE_URL: ${{vars.DATABASEURI}}
      - name: Starting the server and listening
        run: |
          npm run start &
          sleep 5
          curl -s -w "\nHTTP Status: %{http_code}\n" --fail http://localhost:3000/greet
