name: Test Demo Workflow

on: [push]

jobs:
  job-1:
    runs-on: ubuntu-latest
    steps:
      - name: Greeting Step
        run: echo "Hello CI/CD Pipeline"

      - name: Checkout code in VM
        uses: actions/checkout@v4

      - name: Installing Dependencies
        run: npm install

      - name: Starting the server
        run: npm run start